mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('reports/', include('reports.urls')),
    path('admin/', admin.site.urls),
]

mysite/reports/urls.py
from django.urls import path

from . import views

app_name = "reports"
urlpatterns = [
    # ex: /reports/
    path('', views.index, name='index'),
    # ex: /reports/5/
    path('<int:package_id>/', views.detail, name='detail'),
    # ex: /reports/group/
    path("group/", views.group, name = "group"),
    ### wx api
    path("wx_all", views.wx_all, name = "wx_all"),
    path("wx_update", views.wx_update, name = "wx_update"),
    path("wx_create", views.wx_create, name = "wx_create"),
    path("wx_delete", views.wx_delete, name = "wx_delete"),
]

mysite/reports/models.py
from django.db import models


class UserRight(models.Model):
    oid = models.CharField(max_length = 40)
    role = models.CharField(max_length = 20, blank = True)

class MailGroup(models.Model):
    name = models.CharField(max_length = 40)
    owner = models.CharField(max_length = 100, blank = True)
    passcode = models.CharField(max_length = 10, blank = True)
    address = models.CharField(max_length = 160, blank = True)
    created = models.DateTimeField('created at')

    def __str__(self):
        ret = ""
        ret += "Group name:" + self.name + ", "
        ret += "Owner:" + self.owner + ", "
        ret += "Passcode:" + self.passcode + ","
        ret += "Address:" + self.address + ", "
        ret += "Created at:" + str(self.created)
        return ret

class PackageInfo(models.Model):
    name = models.CharField(max_length = 160)
    logistics = models.CharField(max_length = 50)
    tracking = models.CharField(max_length = 20)
    weight = models.IntegerField(default = 0, blank = True)
    volume = models.CharField(max_length = 20, blank = True)
    item_info = models.CharField(max_length = 200, blank = True)
    comment = models.CharField(max_length = 400, blank = True)
    mail_group = models.ForeignKey(MailGroup, on_delete = models.CASCADE)
    oid = models.CharField(max_length = 30, blank = True)
    last_update = models.DateTimeField('last update')
    status = models.CharField(max_length = 20, default = "0")
    image = models.CharField(max_length = 60, blank = True)

    def __str__(self):
        ret = ""
        ret += "name:" + self.name + ", "
        ret += "logistics:" + self.logistics +", "
        ret += "tracking:" + self.tracking + ", "
        ret += "weight:" + str(self.weight) + ", "
        ret += "volume:" + self.volume + ", "
        ret += "item_info:" + self.item_info + ", "
        ret += "comment:" + self.comment + ", "
        ret += "mail_group:" + self.mail_group.name + ", "
        ret += "oid:" + self.oid + ", "
        ret += "last_update:" + str(self.last_update) + ", "
        ret += "status:" + self.status + ", "
        ret += "image:" + self.image
        return ret 

mysite/reports/views.py
from django.shortcuts import render, get_object_or_404
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse

import json
import datetime
from .models import PackageInfo, MailGroup


def index(request):
    package_list = PackageInfo.objects.all()
    group_list = list(set([package.mail_group.name for package in package_list]))
    context = {
        'group_list': group_list,
    }
    return render(request, "reports/index.html", context)

def detail(request, package_id):
    package = get_object_or_404(PackageInfo, pk = package_id)
    return render(request, "reports/detail.html", {"package": package})

def group(request):
    print(request.GET)
    package_list = PackageInfo.objects.filter(group = request.GET["groups"])
    name_package_map = dict()
    for package in package_list:
        if package.name not in name_package_map:
            name_package_map[package.name] = []
        name_package_map[package.name].append(package)
    context = {
        "name_package_map": name_package_map,
    }
    return render(request, "reports/index.html", context)


##################################################

#retrieve all packages of certain user
@csrf_exempt
def wx_all(request):
    req_data = json.loads(request.body)
    print(req_data)
    package_list = PackageInfo.objects.filter(oid = req_data["oid"])
    group_set = set([package.mail_group.name for package in package_list])
    data = dict()
    for package in package_list:
        info = dict()
        info["pk"] = package.pk
        info["name"] = package.name
        info["logistics"] = package.logistics
        info["tracking"] = package.tracking
        info["weight"] = package.weight
        info["volume"] = package.volume
        info["item_info"] = package.item_info
        info["comment"] = package.comment
        info["last_update"] = package.last_update
        info["status"] = package.status
        data[package.mail_group.name] = data.get(package.mail_group.name, list()) + [info]
    return JsonResponse(data)

#update a list of package information
@csrf_exempt
def wx_update(request):
    req_data = json.loads(request.body)
    print(req_data)
    for each in req_data:
        package = PackageInfo.objects.get(pk = each["pk"])
        if "logistics" in each:
            package.logistics = each["logistics"]
        if "tracking" in each:
            package.tracking = each["tracking"]
        if "weight" in each:
            package.weight = each["weight"]
        if "volume" in each:
            package.volume = each["volume"]
        if "item_info" in each:
            package.item_info = each["item_info"]
        if "comment" in each:
            package.comment = each["comment"]
        if "status" in each:
            package.status = each["status"]
        package.last_update = datetime.datetime.now()
        package.save()
    return JsonResponse({"msg": "wx_update"})

#create a list of new package information
@csrf_exempt
def wx_create(request):
    req_data = json.loads(request.body)
    print(req_data)
    for each in req_data:
        package = PackageInfo(name=each["name"],logistics=each["logistics"],tracking=each["tracking"])
        package.mail_group = MailGroup.objects.get(pk = each["mail_group_pk"])
        package.last_update = datetime.datetime.now()
        package.status = each["status"]
        if "weight" in each:
            package.weight = each["weight"]
        if "volume" in each:
            package.volume = each["volume"]
        if "item_info" in each:
            package.item_info = each["item_info"]
        if "comment" in each:
            package.comment = each["comment"]
        package.save()
    return JsonResponse({"msg": "wx_create"})

#delete a list of package information
@csrf_exempt
def wx_delete(request):
    req_data = json.loads(request.body)
    print(req_data)
    for each in req_data:
        package = PackageInfo.objects.get(pk = each["pk"])
        package.delete()
    return JsonResponse({"msg": "wx_delete"})

mysite/reports/templates/reports/detail.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My test page</title>
  </head>
  <body>
    <h1>{{ package.name }}, {{ package.tracking }}</h1>
  </body>
</html>

mysite/reports/templates/reports/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home index</title>
    <style>
    table, th, td {
        border: 1px solid black;
    }
    </style>
  </head>
  <body>
    {% if name_package_map %}
    {% for name, packages in name_package_map.items %}
        <h3>{{name}}</h3>
        <table style="width:80%">
            <tr>
                <th>物流公司</th>
                <th>单号</th>
                <th>重量(kg)</th>
                <th>体积</th>
                <th>物品信息</th>
                <th>备注</th>
                <th>团名</th>
                <th>最近更新</th>
            </tr>
        {% for package in packages %}
            <!--<li><a href='{% url "reports:detail" package.id %}'>{{package.tracking}}</a></li>-->
            <tr>
                <td>{{ package.logistics }}</td>
                <td>{{ package.tracking }}</td>
                <td>{{ package.weight }}</td>
                <td>{{ package.volume }}</td>
                <td>{{ package.item_info }}</td>
                <td>{{ package.comment }}</td>
                <td>{{ package.group }}</td>
                <td>{{ package.last_update }}</td>
            </tr>
        {% endfor %}
        </table>
    {% endfor %}
    {% else %}
        <form action="{% url 'reports:group' %}" method = "get">
        {% csrf_token %}
        <label for="groups">Choose a group:</label>
        <select name="groups" onchange="this.form.submit()">
            <option selected disabled>---</option>
        {% if group_list %}
            {% for group in group_list %}
            <option value="{{group}}">{{ group }}</option>
            {% endfor %}
        {% endif %}
        </select>
        </form>
    {% endif %}
  </body>
</html>